name: C:\Anaconda3\envs\xlsx-conv
dependencies:
- et_xmlfile=1.0.1=py35_0
- jdcal=1.2=py35_1
- openpyxl=2.3.2=py35_0
- pip=8.1.2=py35_0
- python=3.5.2=0
- pywin32=220=py35_1
- setuptools=19.2=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - et-xmlfile==1.0.1
  - future==0.15.2
  - pefile==2016.3.28
  - pyinstaller==3.2

