= xlsx-conv technical documentation

== Setting up a dev environment

Setting up a dev enviroment for xlsx-conv version 1.1+ using Anaconda.

* Install Anaconda with Python 3.6+ (1.1.0 is built with Python 3.6.3)

* Create an environment 
+
----
> conda create --name xlsx-conv
----

* Install runtime dependencies
+
----
> conda install -n xlsx-conv openpyxl=2.4.8
----
Version 1.1.0 is built with openpyxl 2.4.8 and Python 3.6

* Install build time dependencies
+
----
> conda install -n xlsx-conv pip
> activate xlsx-conv
> pip install pyinstaller=3.3
----

When running pyinstaller it will notify about any OS specific dependencies that are missing and prompt to install them.

NOTE: Conda can create an enviroment.yml but that does not seem to be portable over systems. Therefore, the separate commands for setting up a dev environment are document here.

*Historical*

* Version 1.0.0 was build with python 3.5, openpyxl 2.3.2, and pyinstaller 3.2

== Building stand-alone xlsx-conv binaries

Stand-alone binaries can be created using PyInstaller ( http://www.pyinstaller.org/ ).

In the root of the project run:

----
> pyinstaller -F xlsx-conv.py
----
