= xlsx-conv technical documentation

== Setting up a dev environment

Setting up a dev enviroment for xlsx-conv version 1.1+ using Anaconda.

* Install Anaconda with Python 3.6+ (5.1.0 is built with Python 3.6.3)

* Create an environment 
+
----
> conda create --name xlsx-conv
----

* Install runtime dependencies
+
----
> conda install -n xlsx-conv openpyxl=2.5.0
----
+
Search with conda to find the latest available version of openpyxl. Check the openpyxl docs for the latest stable version.
+
----
> conda search -f openpyxl
----
+
Version 1.2.0 is built with Python 3.6.4, openpyxl 2.5.0 and PyInstaller 3.3.1

* Install build time dependencies
+
----
> conda install -n xlsx-conv pip
> activate xlsx-conv
> pip install pyinstaller==3.3.1
----

When running PyInstaller it may notify about any OS specific dependencies that are missing and prompt to install them.

On Linux PyInstaller needs a CPython build with "--enable-shared". It seems Anaconda cannot provide that. Not clear what is the easiest way to get that to work. Pyenv can build a so-called framework enabled version of Python 3.6.3. That does require all build dependencies to be installed.

----
$ env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.3
----

*links*
https://solarianprogrammer.com/2017/06/30/building-python-ubuntu-wsl-debian/

NOTE: Conda can create an enviroment.yml but that does not seem to be portable over systems. Therefore, the separate commands for setting up a dev environment are document here.

*Historical*

* Version 1.1.0 was built with Python 3.6.3, openpyxl 2.4.8, and PyInstaller 3.3
* Version 1.0.0 was build with Python 3.5, openpyxl 2.3.2, and PyInstaller 3.2

== Building stand-alone xlsx-conv binaries

Stand-alone binaries can be created using PyInstaller ( http://www.pyinstaller.org/ ).

In the root of the project run:

----
> pyinstaller -F xlsx-conv.py
----
